import { getSession } from "@auth0/nextjs-auth0"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { fetchMatchesResults } from "../route"
import { MatchFinder } from "./matches"
import { BlankCard } from "./scrims"
import { fetchMatchesUpcoming } from "../route"